"use client";
import Header from "../Header";
import React from "react";
import { useLanguage, translations } from "../LanguageContext";

export default function Datenschutz() {
  const { language } = useLanguage();
  const t = translations[language] || translations.de;
  return (
    <div className="min-h-screen flex flex-col font-sans bg-white text-gray-900">
      <Header />
      <main className="flex-1 px-4 py-12 max-w-3xl mx-auto w-full">
        <h1 className="text-4xl font-extrabold mb-8 text-center" style={{ color: '#3D405B' }}>Datenschutzerklärung</h1>
        <div className="prose prose-lg max-w-none text-[#3D405B]">
          <h2>1. Verantwortlicher für die Datenverarbeitung</h2>
          <p>Verantwortlicher gemäß Art. 4 Abs. 7 DSGVO ist:<br />COzwei GmbH<br />Gutenbergstraße 16a 70176 Stuttgart<br />Deutschland<br />E-Mail: datenschutz@cozwei.de<br />Telefon: 0711 12171034</p>
          <h2>2. Datenschutzbeauftragter</h2>
          <p>Sie erreichen den Datenschutzbeauftragten der COzwei GmbH unter datenschutz@cozwei.de oder per Post unter der oben angegebenen Adresse mit dem Zusatz „Datenschutzbeauftragter".</p>
          <h2>3. Zugriff auf unserer Webseite</h2>
          <p>Beim Besuch unserer Webseite verarbeiten wir personenbezogene Daten, um den reibungslosen bzw. funktionsfähigen sowie sicheren Betrieb unserer Webseite zu garantieren. Dabei können die folgenden Daten verarbeitet werden (sog. Logfiles):<br />- Betriebssystem und aktuelle IP-Adresse (letztes Oktett gekürzt) des Endgeräts, mit dem Sie unsere Webseite besuchen<br />- Browser (Typ, Version und Spracheinstellung)<br />- die abgerufene Datenmenge<br />- Datum und Uhrzeit des Zugriffs<br />- die URL der zuvor besuchten Webseite (Referrer)<br />- die URL der (Unter-)Seite, die Sie auf der Webseite abrufen<br />- den Internet-Service-Provider des zugreifenden Systems</p>
          <p>Die Erhebung der Logfiles ist technisch erforderlich, um Ihnen unsere Webseite anzuzeigen und Stabilität und Sicherheit der Webseite zu gewährleisten. Hierin liegt auch unser berechtigtes Interesse an der Datenverarbeitung. Rechtsgrundlage ist Art. 6 Abs. 1 S. 1 lit. f DSGVO. Das Hosting dieser Webseite erfolgt durch den Dienstleister IONOS SE, Elgendorfer Str. 57,56410 Montabaur, mit dem wir einen Auftragsverarbeitungsvertrag geschlossen haben. Ihre Daten werden in einem deutschen Rechenzentrum verarbeitet und direkt nach der Erhebung anonymisiert.</p>
          <h2>4. Kontaktformulare</h2>
          <p>Wenn Sie über unser Formular mit uns in Kontakt treten, benötigen wir von Ihnen die als Pflichtfelder markierten Daten. Sie können uns außerdem über unsere Webseite zu einer möglichen Förderung Ihres Sanierungsprojekts über die Kreditanstalt für Wiederaufbau (KfW) und dem Bundesministerium für Wirtschaft und Ausfuhrkontrolle (BAFA), sowie für weitere Angebotsanfragen, kontaktieren. Im Rahmen einer solchen Anfrage können wir Ihren Namen, E-Mail-Adresse, Wohnanschrift, Telefonnummer und Informationen zu den zu sanierenden Gebäuden verarbeiten. Die verpflichtenden Angaben, ohne die eine Kontaktaufnahme nicht möglich ist, sind mit einem Stern markiert. Die Verarbeitung der Daten erfolgt aufgrund von Art. 6 Abs. 1 S. 1 lit. b DSGVO im Rahmen der Anbahnung oder Durchführung vorvertraglicher Maßnahmen oder aufgrund unseres berechtigten Interesses an der Bearbeitung und Beantwortung Ihres anderweitigen Anliegens gemäß Art. 6 Abs. 1 S. 1 lit. f DSGVO. Weitere Angaben sind für die Kontaktaufnahme nicht zwingend erforderlich und erfolgen somit freiwillig aufgrund Ihrer Einwilligung gemäß Art. 6 Abs. 1 S. 1 lit. a DSGVO. Ihre personenbezogenen Daten werden – vorbehaltlich gesetzlicher Aufbewahrungsfristen – gelöscht, sobald der Zweck der Speicherung entfällt, Ihr Anliegen also vollständig bearbeitet ist und keine weitere Kommunikation mit Ihnen erforderlich ist oder von Ihnen gewünscht wird.</p>
          <p>Zur Bereitstellung des Kontaktformulars arbeiten wir mit der Microsoft Corporation, One Microsoft Way, Redmond, Washington98052, USA zusammen. Die Verarbeitung der Daten geschieht grundsätzlich in der EU. Da ein Datentransfer zu Microsoft in die USA (Drittland) jedoch nicht vollständig ausgeschlossen werden kann, wurde mit Microsoft ein Auftragsverarbeitungsvertrag unter Anwendung der EU-Standardvertragsklauseln geschlossen. Die EU-Standardvertragsklauseln sind auf der Webseite der Europäischen Kommission verfügbar.</p>
          <h2>5. Google Tag Manager</h2>
          <p>Wir verwenden den Dienst namens Google Tag Manager von Google der Google Ireland Ltd., Gordon House, Barrow Street, Dublin 4, Irland. Mittels des Google Tag Managers können wir Scripts und Plug-Ins schneller und anwenderfreundlicher auf unserer Webseite integrieren. Wir haben einen Auftragsverarbeitungsvertrag mit Google abgeschlossen. Der Google Tag Manager ist ein Hilfsdienst und verarbeitet selbst personenbezogene Daten nur zu technisch notwendigen Zwecken. Der Google Tag Manager sorgt für das Laden anderer Komponenten, die ihrerseits unter Umständen Daten erfassen. Der Google Tag Manager greift nicht auf diese Daten zu. Rechtsgrundlage ist Ihre freiwillige erteilte Einwilligung gemäß Art 6 Abs. 1 lit. a DSGVO. Sie können Ihre Einwilligung über unser Einwilligungs-Management jederzeit, mit Wirkung für die Zukunft, widerrufen. Die Verarbeitung der Daten findet grundsätzlich in der EU statt. Da ein Datentransfer zu Google in den USA (Drittland) jedoch nicht vollständig ausgeschlossen werden kann, haben wir mit Google einen Auftragsverarbeitungsvertrag unter Anwendung der EU-Standardvertragsklauseln geschlossen. Die EU-Standardvertragsklauseln sind auf der Webseite der Europäischen Kommission verfügbar.</p>
          <h2>6. Cookies</h2>
          <p>Bei der Nutzung unserer Webseite werden Cookies auf Ihrem Rechner gespeichert. Bei Cookies handelt es sich um kleine Textdateien, die auf Ihrer Festplatte dem von Ihnen verwendeten Browser zugeordnet gespeichert werden und durch welche der Stelle, die das Cookie setzt, bestimmte Informationen zufließen. Cookies können keine Programme ausführen oder Viren auf Ihren Computer übertragen. Sie dienen dazu, das Internetangebot insgesamt nutzerfreundlicher und effektiver zu machen. Wir nutzen technisch erforderliche Cookies, die für die Bereitstellung der Webseite erforderlich sind. Rechtsgrundlage hierfür ist Art. 6 Abs. 1 S. 1 lit. f DSGVO. Unser berechtigtes Interesse liegt an der technisch einwandfreien und benutzerfreundlichen Darstellung der Webseite. Bei Cookies, die nicht technisch erforderlich sind, basiert die Verarbeitung auf Ihrer Einwilligung gemäß Art. 6 Abs. 1 S. 1 lit. a DSGVO. Einwilligungen werden über unseren Cookie-Banner mittels Ihrer Einwilligung eingeholt. Ihre Einwilligung können Sie jederzeit und ohne Angabe von Gründen mit Wirkung für die Zukunft widerrufen, indem Sie im Cookie-Banner unter der jeweiligen Kategorie das von Ihnen zur Einwilligung gesetzte Häkchen wieder entfernen und die Einstellungen anschließend speichern. Mehr Informationen zu den auf dieser Webseite eingesetzten Cookies finden Sie in unserem Cookie-Banner. Zusätzlich finden Sie nachfolgend Informationen über eingesetzte Dienste, die auf Ihrer Einwilligung beruhen.</p>
          <h3>6.1 Google Analytics</h3>
          <p>Unsere Webseite nutzt Google Analytics, einen Webanalysedienst von Google, Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. Das dafür eingesetzte Cookie ermöglicht eine Analyse der Benutzung unserer Webseite. Google benutzt diese Informationen in unserem Auftrag, um die Nutzung unserer Webseite auszuwerten, um Reports über die Webseitenaktivitäten zusammenzustellen und um weitere mit der Webseitennutzung und der Internetnutzung verbundenen Dienstleistungen gegenüber uns zu erbringen. Die durch das Cookie erzeugten Informationen können dabei auch an einen Server der Google LLC in den USA übertragen und dort gespeichert werden. Auf unserer Webseite wurde Google Analytics daher um den Code „anonymizeIp" erweitert, um eine anonymisierte Erfassung von IP-Adressen (sog. IP-Masking) zu gewährleisten. Dabei wird die IP-Adresse des Nutzers von Google zuvor innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum gekürzt. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA (Drittland) übertragen und dort gekürzt. Die im Rahmen von Google Analytics vom eingesetzten Browser übermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Mit Google haben wir einen Auftragsverarbeitungsvertrag unter Anwendung der EU-Standardvertragsklauseln geschlossen. Die EU-Standardvertragsklauseln sind auf der Webseite der Europäischen Kommission verfügbar. Rechtsgrundlage für den Einsatz von Google Analytics ist Ihre Einwilligung gemäß § 25 Abs. 1 S.1 TTDSG, Art. 6 Abs. 1 S. 1 lit. a DSGVO, die Sie über den Cookie-Banner erteilen und ebenso jederzeit ohne Angaben von Gründen mit Wirkung für die Zukunft im Cookie-Management widerrufen können. Die durch Google Analytics verarbeiteten personenbezogenen Daten werden 14 Monate gespeichert und danach automatisch gelöscht.</p>
          <h3>6.2 Google Adsense</h3>
          <p>Wir verwenden auf unserer Webseite den Anzeigendienst Google Adsense von Google (Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland). Mit Google Adsense ist es uns möglich nachzuverfolgen, ob Sie durch eine von uns geschaltete Anzeige im Google Werbenetz auf unserer Webseite kommen. Im Rahmen der Nutzung von Google Adsense werden personenbezogenen Daten wie Interaktionsdaten mit Werbeanzeigen, auf Ihrem Endgerät gespeicherte Informationen zu bereits angezeigten Werbeinhalten, sowie Ihre IP-Adresse, verarbeitet. Mit Google haben wir einen Auftragsverarbeitungsvertrag unter Anwendung der EU-Standardvertragsklauseln geschlossen. Die EU-Standardvertragsklauseln sind auf der Webseite der Europäischen Kommission verfügbar. Rechtsgrundlage für den Einsatz von Google Analytics ist Ihre Einwilligung gemäß § 25 Abs. 1 S. 1TTDSG, Art. 6 Abs. 1 S. 1 lit. a DSGVO, die Sie über das Cookie-Management erteilen und ebenso jederzeit ohne Angaben von Gründen mit Wirkung für die Zukunft im Cookie-Management widerrufen können. Ihre verarbeiteten personenbezogenen Daten werden durch uns nach 90 Tagen gelöscht.</p>
          <h3>6.3 Google Optimize</h3>
          <p>Auf unserer Webseite setzen wir das Webseitenoptimierungstool Optimize ein. Anbieter ist Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Irland. Wir nutzen den Dienst Google Optimize, um die Attraktivität, den Inhalt und die Funktionalität unserer Webseite zu erhöhen, indem wir neue Funktionen und Inhalte einem prozentualen Anteil unserer Nutzer ausspielen und die Nutzungsänderung statistisch auswerten. Google verarbeitet dabei Ihre Daten teilweise oder vollständig in den USA. Wir haben mit Google einen Auftragsverarbeitungsvertrag unter Anwendung der EU-Standardvertragsklauseln geschlossen. Die EU-Standardvertragsklauseln sind auf der Webseite der Europäischen Kommission verfügbar. Wir nutzen Google Optimize dabei mit aktivierter IP-Anonymisierung, so dass Ihre IP-Adresse von Google innerhalb von Mitgliedstaaten der Europäischen Union oder in anderen Vertragsstaaten des Abkommens über den Europäischen Wirtschaftsraum zuvor gekürzt wird. Nur in Ausnahmefällen wird die volle IP-Adresse an einen Server von Google in den USA übertragen und dort gekürzt. Rechtsgrundlage für den Einsatz von Google Optimize ist Ihre Einwilligung gemäß § 25 Abs. 1 S. 1 TTDSG, Art. 6 Abs. 1 S. 1 lit. aDSGVO, die Sie über das Cookie-Management erteilen und ebenso jederzeit ohne Angaben von Gründen mit Wirkung für die Zukunft im Cookie-Management widerrufen können.</p>
          <h2>7. Ihre Rechte</h2>
          <p>Sie haben das Recht eine Bestätigung darüber zu verlangen, ob Sie betreffende personenbezogene Daten durch uns verarbeitet werden. Ist dies der Fall, geben wir Ihnen gerne Auskunft über diese personenbezogenen Daten und die in Art. 15 DSGVO aufgeführten Informationen. Darüber hinaus steht Ihnen unter den jeweiligen gesetzlichen Voraussetzungen das Recht auf Berichtigung (Art. 16 DSGVO), das Recht auf Einschränkung der Verarbeitung(Art. 18 DSGVO), das Recht auf Löschung (Art. 17 DSGVO), das Recht auf Datenübertragbarkeit (Art. 20 DSGVO) und das Recht Widerspruch gegen die Verarbeitung einzulegen (Art. 21 DSGVO) zu. Beruht die Verarbeitung auf Ihrer Einwilligung, haben Sie das Recht, diese Einwilligung jederzeit zu widerrufen(Art. 7 Abs. 3 DSGVO);die Rechtmäßigkeit der aufgrund der Einwilligung bis zum Widerruf erfolgten Verarbeitung bleibt dabei unberührt. Zur Ausübung Ihrer Betroffenenrechte wenden Sie sich bitte an die unter Ziffer 1 genannten Kontaktmöglichkeiten. Zudem haben Sie jederzeit die Möglichkeit, Ihr Recht auf Beschwerde bei einer zuständigen Aufsichtsbehörde geltend zu machen, wenn Sieder Ansicht sind, dass die Verarbeitung der Sie betreffenden personenbezogenen Daten gegen datenschutzrechtliche Vorschriften verstößt (Art. 77 DSGVO).</p>
          <h2>8. Änderung der Datenschutzerklärung</h2>
          <p>Wir behalten uns das Recht vor, diese Datenschutzerklärung jederzeit unter Beachtung der geltenden Datenschutzvorschriften zu ändern. Derzeitiger Stand ist Juni 2022.</p>
        </div>
      </main>
      <footer className="bg-gray-100 py-8 px-4 mt-8 text-center text-sm text-gray-600">
        <div className="mb-2">COzwei GmbH &bull; Gutenbergstraße 16A, 70176 Stuttgart &bull; Telefon: +49 711 12171034 &bull; E-Mail: mail@cozwei.de</div>
        <div className="flex justify-center gap-4 mb-2">
          <a href="/datenschutz" className="hover:underline">{t.privacy}</a>
          <a href="/impressum" className="hover:underline">{t.imprint}</a>
          <a href="https://www.linkedin.com/company/cozwei" target="_blank" rel="noopener noreferrer" className="hover:underline">{t.linkedin}</a>
        </div>
        <div>© {new Date().getFullYear()} COzwei GmbH</div>
      </footer>
    </div>
  );
} 